# Generated by Django 4.2 on 2025-10-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_category_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
