# Generated by Django 4.2 on 2025-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
