# Generated by Django 4.2 on 2025-10-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_alter_survey_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
